spring:
  application:
    name: isod-feed-ios-notifier

isod:
  api-key: ${ISOD_API_KEY}
  username: ${ISOD_USERNAME}
  url: http://isod.ee.pw.edu.pl/isod-portal/wapi?q=mynewsfull&username=${isod.username}&apikey=${isod.api-key}

pushcut:
  api-key: ${PUSHCUT_API_KEY}
  notification-name: ${PUSHCUT_NAME}
  url: https://api.pushcut.io/v1/notifications/${pushcut.notification-name}

check-interval: 5000

custom-notification: false